---
- hosts: all
  gather_facts: false
  vars:
  - package: IMAGE_HX_AGENT_WIN_25.12.1_EMEA.zip
  - destdir: C:\Users\Administrator\AppData\Local\Temp
  tasks:
  - name: create temp
    win_file:
      path: '{{ destdir }}'
      state: directory
  - name: copy package
    win_copy:
      src: /vagrant/{{ package }}
      dest: "{{ destdir }}\\"
      force: no
  - name: Unzip package
    win_unzip:
      src: "{{ destdir }}\\{{ package }}"
      dest: "{{ destdir }}\\unzip"
      creates: "{{ destdir }}\\unzip"
      delete_archive: yes
  - name: Install package
    win_package:
      path: "{{ destdir }}\\unzip\\xagtSetup_25.12.1_universal.msi"
      product_id: '{37CB321B-20FA-4E1C-A6E1-26CB5690B573}'
      state: present
      register: pkg
  - name: Remove zip
    win_file:
      path: "{{ item }}"
      state: absent
      ignore_errors: yes
      with_items: 
        - "{{ destdir }}\\{{ package }}"
        - "{{ destdir }}\\unzip\\xagtSetup_25.12.1_universal.msi"
        - "{{ destdir }}\\unzip"
      when: pkg|succeeded
